# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookworm', '0002_auto_20170322_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='toRead',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_read',
            field=models.ManyToManyField(related_name='to_read', to='Bookworm.Book'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='to_read',
            field=models.ManyToManyField(blank=True, related_name='has_read', to='Bookworm.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(),
        ),
    ]
